name: Deploy to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # required for OIDC
  contents: read    # required for checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS creds from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::673181687487:role/GitHubActionsS3DeployRole
          aws-region: ap-south-1

      - name: Sync files to S3
        run: aws s3 sync . s3://rajveer.quantsynapse.com --delete
